
### Analyse exploratoire des données immobilières
##### 1. Introduction
Ce notebook présente l'analyse exploratoire des données immobilières issues de plusieurs sources.
L'objectif est de comprendre la structure des données, d'examiner leur qualité, d'identifier les valeurs manquantes et les éventuelles anomalies, puis de décrire les principales caractéristiques des annonces immobilières.
L'analyse s'appuie sur les fichiers produits par le pipeline de nettoyage du projet `immo-analyse`.

In [8]:

import pandas as pd
import json
from pathlib import Path

# Définir le dossier principal du projet
DOSSIER_PROJET = Path.cwd().parent

# Si le notebook est exécuté depuis la racine du projet,
# on adapte automatiquement le chemin.
if (Path.cwd() / "data").exists():
    DOSSIER_PROJET = Path.cwd()

DOSSIER_DONNEES = DOSSIER_PROJET / "data" / "processed"

print("Dossier du projet :", DOSSIER_PROJET)
print("Dossier des données traitées :", DOSSIER_DONNEES)

Dossier du projet : c:\Users\hp\Documents\immo-analyse
Dossier des données traitées : c:\Users\hp\Documents\immo-analyse\data\processed


#### 2. Chargement des données
Cette section permet de charger les annonces conformes et les annonces mises en quarantaine par le pipeline de nettoyage.

In [9]:

# Chemins des fichiers
fichier_conformes = DOSSIER_DONNEES / "annonces_conformes.csv"
fichier_quarantaine = DOSSIER_DONNEES / "annonces_quarantaine.csv"

# Charger les fichiers CSV
annonces_conformes = pd.read_csv(fichier_conformes)
annonces_quarantaine = pd.read_csv(fichier_quarantaine)

print("Données chargées avec succès !")
print("Nombre d'annonces conformes :", len(annonces_conformes))
print("Nombre d'annonces en quarantaine :", len(annonces_quarantaine))

Données chargées avec succès !
Nombre d'annonces conformes : 2997
Nombre d'annonces en quarantaine : 187


#### 3. Exploration générale des données
Nous examinons les premières lignes, les dimensions et les types de données afin de mieux comprendre la structure des fichiers.

In [10]:

# Afficher les premières lignes
display(annonces_conformes.head())

# Dimensions du jeu de données
print("Dimensions :", annonces_conformes.shape)

# Noms des colonnes
print("\nColonnes disponibles :")
print(annonces_conformes.columns.tolist())

# Types des colonnes
print("\nTypes de données :")
annonces_conformes.info()

,id_source,date,type_transaction,categorie,region,ville,quartier,prix,devise,surface,pieces,salles_bain,description,statut,date_expiration,source,chambres,Commercial,motif_quarantaine,avertissements
0,PLT-00001,2020-07-03,vente,Appartement,Tambacounda,Tambacounda,Nord,60581000.0,FCFA,173.3,1.0,1.0,Appartement à Tambacounda. Contact via platefo...,Vendu,2020-08-05,plateforme,NaN,NaN,NaN,NaN
1,PLT-00002,2022-09-15,vente,Maison,Kolda,Kolda,Résidentiel,57620000.0,FCFA,89.6,5.0,3.0,Maison à Kolda. Contact via plateforme.,Vendu,2022-11-19,plateforme,NaN,NaN,NaN,NaN
2,PLT-00003,2019-01-15,vente,Terrain,Diourbel,Touba,Centre,9688000.0,FCFA,1457.3,0.0,0.0,Terrain à Touba. Contact via plateforme.,Vendu,2019-04-23,plateforme,NaN,NaN,NaN,NaN
3,PLT-00004,2025-01-18,vente,Appartement,Thiès,Joal-Fadiouth,Sud,42273000.0,FCFA,69.8,3.0,2.0,Appartement à Joal-Fadiouth. Contact via plate...,En vente,2025-03-18,plateforme,NaN,NaN,NaN,NaN
4,PLT-00005,2022-02-03,vente,Studio,Kaffrine,Kaffrine,Centre,26254000.0,FCFA,31.6,3.0,2.0,Studio à Kaffrine. Contact via plateforme.,Vendu,2022-03-26,plateforme,NaN,NaN,NaN,NaN

Dimensions : (2997, 20)

Colonnes disponibles :
['id_source', 'date', 'type_transaction', 'categorie', 'region', 'ville', 'quartier', 'prix', 'devise', 'surface', 'pieces', 'salles_bain', 'description', 'statut', 'date_expiration', 'source', 'chambres', 'Commercial', 'motif_quarantaine', 'avertissements']

Types de données :
<class 'pandas.DataFrame'>
RangeIndex: 2997 entries, 0 to 2996
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_source          2997 non-null   str
 1   date               2997 non-null   str
 2   type_transaction   1458 non-null   str
 3   categorie          2997 non-null   str
 4   region             2997 non-null   str
 5   ville              2989 non-null   str
 6   quartier           863 non-null    str
 7   prix               2997 non-null   float64
 8   devise             863 non-null    str
 9   surface            2997 non-null   float64
 10  pieces             863 non-null    float64
 11  salles_bain        2607 non-null   float64
 12  description        700 non-null    str
 13  statut             2479 non-null   str
 14  date_expiration    863 non-null    str
 15  source             2997 non-null   str
 16  chambres           2134 non-null   float64
 17  Commercial         631 non-null    str
 18  motif_quarantaine  0 non-null      float64
 19  avertissements     50 non-null     str
dtypes: float64(6), str(14)
memory usage: 468.4 KB

#### 4. Analyse de la qualité des données
##### 4.1. Valeurs manquantes
Cette analyse permet d'identifier les colonnes contenant des valeurs manquantes dans les annonces conformes et les annonces en quarantaine.

In [11]:

# Nombre de valeurs manquantes par colonne
manquantes_conformes = annonces_conformes.isnull().sum()
manquantes_quarantaine = annonces_quarantaine.isnull().sum()

print("Valeurs manquantes dans les annonces conformes :")
display(manquantes_conformes[manquantes_conformes > 0].to_frame("Nombre de valeurs manquantes"))

print("Valeurs manquantes dans les annonces en quarantaine :")
display(manquantes_quarantaine[manquantes_quarantaine > 0].to_frame("Nombre de valeurs manquantes"))

Valeurs manquantes dans les annonces conformes :

                   Nombre de valeurs manquantes
type_transaction                           1539
ville                                         8
quartier                                   2134
devise                                     2134
pieces                                     2134
salles_bain                                 390
description                                2297
statut                                      518
date_expiration                            2134
chambres                                    863
Commercial                                 2366
motif_quarantaine                          2997
avertissements                             2947

Valeurs manquantes dans les annonces en quarantaine :

                  Nombre de valeurs manquantes
type_transaction                            39
quartier                                   175
prix                                        93
devise                                     175
surface                                     84
pieces                                     175
salles_bain                                 20
description                                177
statut                                      10
date_expiration                            175
chambres                                    12
Commercial                                 178
avertissements                             177


#### 4.2. Recherche des doublons
Nous recherchons les lignes entièrement identiques et les identifiants répétés afin de repérer d'éventuels doublons dans les données.

In [12]:

# Nombre de lignes entièrement identiques
print(
    "Lignes dupliquées dans les annonces conformes :",
    annonces_conformes.duplicated().sum()
)

print(
    "Lignes dupliquées dans la quarantaine :",
    annonces_quarantaine.duplicated().sum()
)

# Vérifier les identifiants répétés si la colonne existe
if "id_source" in annonces_conformes.columns:
    print(
        "Identifiants répétés parmi les annonces conformes :",
        annonces_conformes["id_source"].duplicated().sum()
    )
else:
    print("La colonne id_source n'est pas présente dans les annonces conformes.")

Lignes dupliquées dans les annonces conformes : 14
Lignes dupliquées dans la quarantaine : 1
Identifiants répétés parmi les annonces conformes : 14

In [13]:

# Afficher les lignes entièrement dupliquées
doublons_conformes = annonces_conformes[
    annonces_conformes.duplicated(keep=False)
]

print("Lignes concernées par des doublons dans les annonces conformes :")
display(doublons_conformes.sort_values("id_source"))

# Afficher les identifiants répétés
identifiants_repetes = annonces_conformes[
    annonces_conformes["id_source"].duplicated(keep=False)
]

print("Annonces ayant un identifiant répété :")
display(identifiants_repetes.sort_values("id_source"))

Lignes concernées par des doublons dans les annonces conformes :

,id_source,date,type_transaction,categorie,region,ville,quartier,prix,devise,surface,pieces,salles_bain,description,statut,date_expiration,source,chambres,Commercial,motif_quarantaine,avertissements
57,PLT-00058,2024-04-04,vente,Appartement,Diourbel,Mbacké,Sud,116544000.0,FCFA,160.2,5.0,2.0,Appartement à Mbacké. Contact via plateforme.,En vente,2024-06-27,plateforme,NaN,NaN,NaN,NaN
852,PLT-00058,2024-04-04,vente,Appartement,Diourbel,Mbacké,Sud,116544000.0,FCFA,160.2,5.0,2.0,Appartement à Mbacké. Contact via plateforme.,En vente,2024-06-27,plateforme,NaN,NaN,NaN,NaN
167,PLT-00171,2023-03-02,vente,Studio,Louga,Linguère,Populaire,41498000.0,FCFA,51.5,3.0,2.0,Studio à Linguère. Contact via plateforme.,Vendu,2023-06-18,plateforme,NaN,NaN,NaN,NaN
857,PLT-00171,2023-03-02,vente,Studio,Louga,Linguère,Populaire,41498000.0,FCFA,51.5,3.0,2.0,Studio à Linguère. Contact via plateforme.,Vendu,2023-06-18,plateforme,NaN,NaN,NaN,NaN
391,PLT-00398,2024-07-12,vente,Appartement,Fatick,Kaolack-Fatick,Résidentiel,31332000.0,FCFA,115.0,3.0,3.0,NaN,Vendu,2024-09-21,plateforme,NaN,NaN,NaN,NaN
855,PLT-00398,2024-07-12,vente,Appartement,Fatick,Kaolack-Fatick,Résidentiel,31332000.0,FCFA,115.0,3.0,3.0,NaN,Vendu,2024-09-21,plateforme,NaN,NaN,NaN,NaN
484,PLT-00491,2021-04-23,vente,Appartement,Fatick,Kaolack-Fatick,Est,52761000.0,FCFA,168.0,6.0,2.0,Appartement à Kaolack-Fatick. Contact via plat...,En vente,2021-07-24,plateforme,NaN,NaN,NaN,NaN
861,PLT-00491,2021-04-23,vente,Appartement,Fatick,Kaolack-Fatick,Est,52761000.0,FCFA,168.0,6.0,2.0,Appartement à Kaolack-Fatick. Contact via plat...,En vente,2021-07-24,plateforme,NaN,NaN,NaN,NaN
487,PLT-00494,2025-10-10,vente,Appartement,Fatick,Fatick,Centre,34171000.0,FCFA,77.7,2.0,2.0,Appartement à Fatick. Contact via plateforme.,En vente,2025-12-18,plateforme,NaN,NaN,NaN,NaN
859,PLT-00494,2025-10-10,vente,Appartement,Fatick,Fatick,Centre,34171000.0,FCFA,77.7,2.0,2.0,Appartement à Fatick. Contact via plateforme.,En vente,2025-12-18,plateforme,NaN,NaN,NaN,NaN
536,PLT-00544,2022-11-19,vente,Maison,Saint-Louis,Saint-Louis,Nord,126817000.0,FCFA,162.9,1.0,2.0,Maison à Saint-Louis. Contact via plateforme.,Vendu,2023-03-05,plateforme,NaN,NaN,NaN,NaN
860,PLT-00544,2022-11-19,vente,Maison,Saint-Louis,Saint-Louis,Nord,126817000.0,FCFA,162.9,1.0,2.0,Maison à Saint-Louis. Contact via plateforme.,Vendu,2023-03-05,plateforme,NaN,NaN,NaN,NaN
862,PLT-00625,2024-01-26,location,Appartement,Sédhiou,Goudomp,Centre,260000.0,FCFA/mois,131.5,4.0,2.0,Appartement à Goudomp. Contact via plateforme.,Disponible,2024-05-07,plateforme,NaN,NaN,NaN,NaN
617,PLT-00625,2024-01-26,location,Appartement,Sédhiou,Goudomp,Centre,260000.0,FCFA/mois,131.5,4.0,2.0,Appartement à Goudomp. Contact via plateforme.,Disponible,2024-05-07,plateforme,NaN,NaN,NaN,NaN
854,PLT-00656,2024-05-20,location,Maison,Matam,Kanel,Sud,695000.0,FCFA/mois,192.5,2.0,4.0,Maison à Kanel. Contact via plateforme.,En vente,2024-08-15,plateforme,NaN,NaN,NaN,NaN
648,PLT-00656,2024-05-20,location,Maison,Matam,Kanel,Sud,695000.0,FCFA/mois,192.5,2.0,4.0,Maison à Kanel. Contact via plateforme.,En vente,2024-08-15,plateforme,NaN,NaN,NaN,NaN
849,PLT-00692,2020-05-14,vente,Maison,Tambacounda,Goudiry,Est,127465000.0,FCFA,106.0,1.0,4.0,Maison à Goudiry. Contact via plateforme.,Vendu,2020-07-26,plateforme,NaN,NaN,NaN,NaN
682,PLT-00692,2020-05-14,vente,Maison,Tambacounda,Goudiry,Est,127465000.0,FCFA,106.0,1.0,4.0,Maison à Goudiry. Contact via plateforme.,Vendu,2020-07-26,plateforme,NaN,NaN,NaN,NaN
851,PLT-00711,2019-12-08,vente,Villa,Saint-Louis,Richard-Toll,Sud,193884000.0,FCFA,421.6,4.0,1.0,Villa à Richard-Toll. Contact via plateforme.,En vente,2020-03-03,plateforme,NaN,NaN,NaN,NaN
701,PLT-00711,2019-12-08,vente,Villa,Saint-Louis,Richard-Toll,Sud,193884000.0,FCFA,421.6,4.0,1.0,Villa à Richard-Toll. Contact via plateforme.,En vente,2020-03-03,plateforme,NaN,NaN,NaN,NaN
705,PLT-00716,2018-05-24,vente,Appartement,Tambacounda,Tambacounda,Résidentiel,42029000.0,FCFA,138.7,1.0,3.0,NaN,Vendu,2018-07-31,plateforme,NaN,NaN,NaN,NaN
856,PLT-00716,2018-05-24,vente,Appartement,Tambacounda,Tambacounda,Résidentiel,42029000.0,FCFA,138.7,1.0,3.0,NaN,Vendu,2018-07-31,plateforme,NaN,NaN,NaN,NaN
778,PLT-00790,2025-08-07,location,Terrain,Dakar,Pikine,Ouest,110000.0,FCFA/mois,566.6,0.0,0.0,Terrain à Pikine. Contact via plateforme.,Loué,2025-11-02,plateforme,NaN,NaN,NaN,NaN
853,PLT-00790,2025-08-07,location,Terrain,Dakar,Pikine,Ouest,110000.0,FCFA/mois,566.6,0.0,0.0,Terrain à Pikine. Contact via plateforme.,Loué,2025-11-02,plateforme,NaN,NaN,NaN,NaN
858,PLT-00799,2024-10-23,location,Maison,Saint-Louis,Podor,Ouest,490000.0,FCFA/mois,219.3,6.0,4.0,Maison à Podor. Contact via plateforme.,Disponible,2024-12-21,plateforme,NaN,NaN,NaN,NaN
787,PLT-00799,2024-10-23,location,Maison,Saint-Louis,Podor,Ouest,490000.0,FCFA/mois,219.3,6.0,4.0,Maison à Podor. Contact via plateforme.,Disponible,2024-12-21,plateforme,NaN,NaN,NaN,NaN
850,PLT-00801,2024-02-05,vente,Appartement,Dakar,Keur Massar,Est,36970000.0,FCFA,71.5,1.0,4.0,Appartement à Keur Massar. Contact via platefo...,Sous offre,2024-04-20,plateforme,NaN,NaN,NaN,NaN
789,PLT-00801,2024-02-05,vente,Appartement,Dakar,Keur Massar,Est,36970000.0,FCFA,71.5,1.0,4.0,Appartement à Keur Massar. Contact via platefo...,Sous offre,2024-04-20,plateforme,NaN,NaN,NaN,NaN

Annonces ayant un identifiant répété :

,id_source,date,type_transaction,categorie,region,ville,quartier,prix,devise,surface,pieces,salles_bain,description,statut,date_expiration,source,chambres,Commercial,motif_quarantaine,avertissements
57,PLT-00058,2024-04-04,vente,Appartement,Diourbel,Mbacké,Sud,116544000.0,FCFA,160.2,5.0,2.0,Appartement à Mbacké. Contact via plateforme.,En vente,2024-06-27,plateforme,NaN,NaN,NaN,NaN
852,PLT-00058,2024-04-04,vente,Appartement,Diourbel,Mbacké,Sud,116544000.0,FCFA,160.2,5.0,2.0,Appartement à Mbacké. Contact via plateforme.,En vente,2024-06-27,plateforme,NaN,NaN,NaN,NaN
167,PLT-00171,2023-03-02,vente,Studio,Louga,Linguère,Populaire,41498000.0,FCFA,51.5,3.0,2.0,Studio à Linguère. Contact via plateforme.,Vendu,2023-06-18,plateforme,NaN,NaN,NaN,NaN
857,PLT-00171,2023-03-02,vente,Studio,Louga,Linguère,Populaire,41498000.0,FCFA,51.5,3.0,2.0,Studio à Linguère. Contact via plateforme.,Vendu,2023-06-18,plateforme,NaN,NaN,NaN,NaN
391,PLT-00398,2024-07-12,vente,Appartement,Fatick,Kaolack-Fatick,Résidentiel,31332000.0,FCFA,115.0,3.0,3.0,NaN,Vendu,2024-09-21,plateforme,NaN,NaN,NaN,NaN
855,PLT-00398,2024-07-12,vente,Appartement,Fatick,Kaolack-Fatick,Résidentiel,31332000.0,FCFA,115.0,3.0,3.0,NaN,Vendu,2024-09-21,plateforme,NaN,NaN,NaN,NaN
484,PLT-00491,2021-04-23,vente,Appartement,Fatick,Kaolack-Fatick,Est,52761000.0,FCFA,168.0,6.0,2.0,Appartement à Kaolack-Fatick. Contact via plat...,En vente,2021-07-24,plateforme,NaN,NaN,NaN,NaN
861,PLT-00491,2021-04-23,vente,Appartement,Fatick,Kaolack-Fatick,Est,52761000.0,FCFA,168.0,6.0,2.0,Appartement à Kaolack-Fatick. Contact via plat...,En vente,2021-07-24,plateforme,NaN,NaN,NaN,NaN
487,PLT-00494,2025-10-10,vente,Appartement,Fatick,Fatick,Centre,34171000.0,FCFA,77.7,2.0,2.0,Appartement à Fatick. Contact via plateforme.,En vente,2025-12-18,plateforme,NaN,NaN,NaN,NaN
859,PLT-00494,2025-10-10,vente,Appartement,Fatick,Fatick,Centre,34171000.0,FCFA,77.7,2.0,2.0,Appartement à Fatick. Contact via plateforme.,En vente,2025-12-18,plateforme,NaN,NaN,NaN,NaN
536,PLT-00544,2022-11-19,vente,Maison,Saint-Louis,Saint-Louis,Nord,126817000.0,FCFA,162.9,1.0,2.0,Maison à Saint-Louis. Contact via plateforme.,Vendu,2023-03-05,plateforme,NaN,NaN,NaN,NaN
860,PLT-00544,2022-11-19,vente,Maison,Saint-Louis,Saint-Louis,Nord,126817000.0,FCFA,162.9,1.0,2.0,Maison à Saint-Louis. Contact via plateforme.,Vendu,2023-03-05,plateforme,NaN,NaN,NaN,NaN
862,PLT-00625,2024-01-26,location,Appartement,Sédhiou,Goudomp,Centre,260000.0,FCFA/mois,131.5,4.0,2.0,Appartement à Goudomp. Contact via plateforme.,Disponible,2024-05-07,plateforme,NaN,NaN,NaN,NaN
617,PLT-00625,2024-01-26,location,Appartement,Sédhiou,Goudomp,Centre,260000.0,FCFA/mois,131.5,4.0,2.0,Appartement à Goudomp. Contact via plateforme.,Disponible,2024-05-07,plateforme,NaN,NaN,NaN,NaN
854,PLT-00656,2024-05-20,location,Maison,Matam,Kanel,Sud,695000.0,FCFA/mois,192.5,2.0,4.0,Maison à Kanel. Contact via plateforme.,En vente,2024-08-15,plateforme,NaN,NaN,NaN,NaN
648,PLT-00656,2024-05-20,location,Maison,Matam,Kanel,Sud,695000.0,FCFA/mois,192.5,2.0,4.0,Maison à Kanel. Contact via plateforme.,En vente,2024-08-15,plateforme,NaN,NaN,NaN,NaN
849,PLT-00692,2020-05-14,vente,Maison,Tambacounda,Goudiry,Est,127465000.0,FCFA,106.0,1.0,4.0,Maison à Goudiry. Contact via plateforme.,Vendu,2020-07-26,plateforme,NaN,NaN,NaN,NaN
682,PLT-00692,2020-05-14,vente,Maison,Tambacounda,Goudiry,Est,127465000.0,FCFA,106.0,1.0,4.0,Maison à Goudiry. Contact via plateforme.,Vendu,2020-07-26,plateforme,NaN,NaN,NaN,NaN
851,PLT-00711,2019-12-08,vente,Villa,Saint-Louis,Richard-Toll,Sud,193884000.0,FCFA,421.6,4.0,1.0,Villa à Richard-Toll. Contact via plateforme.,En vente,2020-03-03,plateforme,NaN,NaN,NaN,NaN
701,PLT-00711,2019-12-08,vente,Villa,Saint-Louis,Richard-Toll,Sud,193884000.0,FCFA,421.6,4.0,1.0,Villa à Richard-Toll. Contact via plateforme.,En vente,2020-03-03,plateforme,NaN,NaN,NaN,NaN
705,PLT-00716,2018-05-24,vente,Appartement,Tambacounda,Tambacounda,Résidentiel,42029000.0,FCFA,138.7,1.0,3.0,NaN,Vendu,2018-07-31,plateforme,NaN,NaN,NaN,NaN
856,PLT-00716,2018-05-24,vente,Appartement,Tambacounda,Tambacounda,Résidentiel,42029000.0,FCFA,138.7,1.0,3.0,NaN,Vendu,2018-07-31,plateforme,NaN,NaN,NaN,NaN
778,PLT-00790,2025-08-07,location,Terrain,Dakar,Pikine,Ouest,110000.0,FCFA/mois,566.6,0.0,0.0,Terrain à Pikine. Contact via plateforme.,Loué,2025-11-02,plateforme,NaN,NaN,NaN,NaN
853,PLT-00790,2025-08-07,location,Terrain,Dakar,Pikine,Ouest,110000.0,FCFA/mois,566.6,0.0,0.0,Terrain à Pikine. Contact via plateforme.,Loué,2025-11-02,plateforme,NaN,NaN,NaN,NaN
858,PLT-00799,2024-10-23,location,Maison,Saint-Louis,Podor,Ouest,490000.0,FCFA/mois,219.3,6.0,4.0,Maison à Podor. Contact via plateforme.,Disponible,2024-12-21,plateforme,NaN,NaN,NaN,NaN
787,PLT-00799,2024-10-23,location,Maison,Saint-Louis,Podor,Ouest,490000.0,FCFA/mois,219.3,6.0,4.0,Maison à Podor. Contact via plateforme.,Disponible,2024-12-21,plateforme,NaN,NaN,NaN,NaN
850,PLT-00801,2024-02-05,vente,Appartement,Dakar,Keur Massar,Est,36970000.0,FCFA,71.5,1.0,4.0,Appartement à Keur Massar. Contact via platefo...,Sous offre,2024-04-20,plateforme,NaN,NaN,NaN,NaN
789,PLT-00801,2024-02-05,vente,Appartement,Dakar,Keur Massar,Est,36970000.0,FCFA,71.5,1.0,4.0,Appartement à Keur Massar. Contact via platefo...,Sous offre,2024-04-20,plateforme,NaN,NaN,NaN,NaN


**Constat :** l'analyse révèle 14 lignes entièrement dupliquées dans les annonces conformes et une ligne dupliquée dans les annonces en quarantaine. Le contrôle des identifiants signale également 14 occurrences répétées parmi les annonces conformes.
**Action à prévoir :** examiner les identifiants concernés et vérifier les règles métier avant toute suppression. Les doublons détectés doivent être documentés afin de garantir la traçabilité du nettoyage.

In [14]:

print("Colonnes disponibles :")
print(annonces_conformes.columns.tolist())

Colonnes disponibles :
['id_source', 'date', 'type_transaction', 'categorie', 'region', 'ville', 'quartier', 'prix', 'devise', 'surface', 'pieces', 'salles_bain', 'description', 'statut', 'date_expiration', 'source', 'chambres', 'Commercial', 'motif_quarantaine', 'avertissements']

#### 5. Analyse descriptive des annonces immobilières
##### 5.1. Analyse des prix et des surfaces
Cette section présente les principales statistiques descriptives des prix et des surfaces des annonces conformes. Elle permet de comprendre la répartition des prix et la diversité des surfaces proposées.

In [15]:

# Convertir les prix en valeurs numériques
prix = pd.to_numeric(
    annonces_conformes["prix"]
    .astype(str)
    .str.replace(" ", "", regex=False)
    .str.replace(",", ".", regex=False),
    errors="coerce"
)

# Convertir les surfaces en valeurs numériques
surface = pd.to_numeric(
    annonces_conformes["surface"]
    .astype(str)
    .str.replace(" ", "", regex=False)
    .str.replace(",", ".", regex=False),
    errors="coerce"
)

# Calculer les statistiques descriptives
statistiques = pd.DataFrame({
    "Prix": prix.describe(),
    "Surface": surface.describe()
})

display(statistiques)

               Prix      Surface
count  2.997000e+03  2997.000000
mean   8.872976e+07   240.726126
std    9.778527e+07   292.037592
min    4.000000e+04    10.200000
25%    2.268100e+07    72.000000
50%    5.963300e+07   147.000000
75%    1.161160e+08   246.400000
max    5.675590e+08  1494.800000

In [16]:

# Calculer le prix au mètre carré lorsque le prix et la surface sont valides
prix_m2 = prix / surface

prix_m2 = prix_m2.where(
    (prix > 0) & (surface > 0)
)

print("Statistiques du prix au mètre carré :")
display(prix_m2.describe())

# Ajouter cette information au tableau d'analyse
annonces_analyse = annonces_conformes.copy()
annonces_analyse["prix_m2"] = prix_m2

display(
    annonces_analyse[
        ["ville", "categorie", "prix", "surface", "prix_m2"]
    ].head(10)
)

Statistiques du prix au mètre carré :

count    2.997000e+03
mean     6.245732e+05
std      5.794831e+05
min      3.728308e+01
25%      1.447321e+05
50%      5.310678e+05
75%      8.929160e+05
max      4.603188e+06
dtype: float64

                ville    categorie         prix  surface       prix_m2
0         Tambacounda  Appartement   60581000.0    173.3  3.495730e+05
1               Kolda       Maison   57620000.0     89.6  6.430804e+05
2               Touba      Terrain    9688000.0   1457.3  6.647911e+03
3       Joal-Fadiouth  Appartement   42273000.0     69.8  6.056304e+05
4            Kaffrine       Studio   26254000.0     31.6  8.308228e+05
5  Médina Yoro Foulah  Appartement   52754000.0     94.5  5.582434e+05
6             Kébémer  Appartement     240000.0    114.4  2.097902e+03
7           Vélingara       Maison  123094000.0     92.4  1.332186e+06
8             Goudomp      Chambre   13895000.0     18.8  7.390957e+05
9             Goudiry       Maison   39986000.0    232.8  1.717612e+05


##### 5.2. Interprétation des statistiques descriptives
L'analyse porte sur 2 997 annonces conformes. Le prix moyen est d'environ 88,73 millions, tandis que le prix médian est de 59,63 millions. L'écart entre ces deux indicateurs suggère une distribution des prix influencée par des annonces de valeur élevée.
La surface moyenne est de 240,73, contre une médiane de 147. Cette différence indique une forte variabilité des surfaces et la présence possible de grandes propriétés.
Le prix moyen au mètre carré est d'environ 624 573, contre une médiane de 531 068. Les valeurs minimales et maximales observées nécessitent des contrôles complémentaires.
Ces résultats restent descriptifs. Avant toute comparaison entre villes ou catégories, il convient de vérifier les devises, les unités et la cohérence des valeurs extrêmes.


#### 6. Répartition des annonces
##### 6.1. Répartition par ville et par catégorie
Cette analyse permet d'identifier les villes et les catégories de biens les plus représentées dans les annonces conformes.

In [17]:

# Les 10 villes les plus représentées
print("Top 10 des villes par nombre d'annonces :")
display(
    annonces_conformes["ville"]
    .value_counts()
    .head(10)
    .rename_axis("Ville")
    .reset_index(name="Nombre d'annonces")
)

# Répartition par catégorie
print("Répartition des annonces par catégorie :")
display(
    annonces_conformes["categorie"]
    .value_counts()
    .rename_axis("Catégorie")
    .reset_index(name="Nombre d'annonces")
)

Top 10 des villes par nombre d'annonces :

                Ville  Nombre d'annonces
0             Kébémer                 91
1               Kanel                 83
2           Koungheul                 82
3          Ourossogui                 80
4            Kaffrine                 79
5  Médina Yoro Foulah                 79
6             Goudomp                 79
7          Bounkiling                 79
8            Linguère                 78
9             Bignona                 78

Répartition des annonces par catégorie :

           Catégorie  Nombre d'annonces
0        Appartement                677
1             Maison                613
2              Villa                499
3            Terrain                418
4             Studio                342
5            Chambre                169
6   Local commercial                125
7   LOCAL COMMERCIAL                 34
8        APPARTEMENT                 29
9            TERRAIN                 22
10            MAISON                 21
11             VILLA                 16
12            STUDIO                 15
13           CHAMBRE                 12
14            appart                  5


#### 6.2. Interprétation de la répartition
Kébémer est la ville la plus représentée parmi les annonces conformes, avec 91 annonces, suivie de Kanel avec 83 annonces et de Koungheul avec 82 annonces. Les effectifs des dix premières villes restent relativement proches.
Concernant les catégories, les appartements sont les plus représentés avec 677 annonces, suivis des maisons avec 613 annonces, des villas avec 499 annonces et des terrains avec 418 annonces.
L'analyse révèle également des différences d'écriture pour certaines catégories, notamment les majuscules et les abréviations. Ces variations peuvent fragmenter les résultats statistiques. Une harmonisation des catégories est donc nécessaire pour améliorer la cohérence des analyses.
Ces résultats décrivent le jeu de données étudié et ne constituent pas, à eux seuls, une estimation représentative du marché immobilier sénégalais.

In [18]:
# Examiner les valeurs distinctes des catégories
print("Catégories distinctes dans les annonces conformes :")
display(
    annonces_conformes["categorie"]
    .value_counts()
    .rename_axis("Catégorie")
    .reset_index(name="Nombre d'annonces")
)

# Examiner les espaces et les différences de casse
print("\nCatégories normalisées uniquement pour comparaison :")
display(
    annonces_conformes["categorie"]
    .dropna()
    .astype(str)
    .str.strip()
    .str.lower()
    .value_counts()
    .rename_axis("Catégorie normalisée")
    .reset_index(name="Nombre d'annonces")
)

Catégories distinctes dans les annonces conformes :

           Catégorie  Nombre d'annonces
0        Appartement                677
1             Maison                613
2              Villa                499
3            Terrain                418
4             Studio                342
5            Chambre                169
6   Local commercial                125
7   LOCAL COMMERCIAL                 34
8        APPARTEMENT                 29
9            TERRAIN                 22
10            MAISON                 21
11             VILLA                 16
12            STUDIO                 15
13           CHAMBRE                 12
14            appart                  5

Catégories normalisées uniquement pour comparaison :

  Catégorie normalisée  Nombre d'annonces
0          appartement                706
1               maison                634
2                villa                515
3              terrain                440
4               studio                357
5              chambre                181
6     local commercial                159
7               appart                  5


#### 6.3. Contrôle de la cohérence des catégories
L'analyse initiale a révélé plusieurs variantes d'écriture pour les catégories immobilières. Après une harmonisation temporaire de la casse et des espaces, les 2 997 annonces se répartissent entre huit libellés distincts.
Les appartements représentent 706 annonces, les maisons 634 et les villas 515. 
L'abréviation « appart » reste distincte de « appartement » et concerne cinq annonces.
Cette harmonisation a été effectuée uniquement pour l'analyse exploratoire. La correction définitive doit être intégrée au référentiel ou au mécanisme de normalisation du pipeline, puis vérifiée en relançant les tests.


#### 7. Analyse complémentaire


##### 7.1. Répartition des annonces par source
Cette analyse permet d'identifier la contribution de chaque source au jeu de données final et de mieux comprendre l'origine des annonces immobilières.

In [19]:

# Répartition des annonces par source
repartition_sources = (
    annonces_conformes["source"]
    .value_counts()
    .rename_axis("Source")
    .reset_index(name="Nombre d'annonces")
)

display(repartition_sources)

# Répartition des annonces par type de transaction
print("Répartition par type de transaction :")

display(
    annonces_conformes["type_transaction"]
    .value_counts()
    .rename_axis("Type de transaction")
    .reset_index(name="Nombre d'annonces")
)

         Source  Nombre d'annonces
0    plateforme                863
1        agence                631
2  particuliers                595
3    historique                518
4      notaires                390

Répartition par type de transaction :

  Type de transaction  Nombre d'annonces
0               vente               1111
1            location                347

In [20]:

# Examiner toutes les modalités, y compris les valeurs manquantes
print("Valeurs de la colonne type_transaction :")

display(
    annonces_conformes["type_transaction"]
    .value_counts(dropna=False)
    .rename_axis("Type de transaction")
    .reset_index(name="Nombre d'annonces")
)

# Calculer le nombre de valeurs manquantes
print(
    "Valeurs manquantes :",
    annonces_conformes["type_transaction"].isna().sum()
)

Valeurs de la colonne type_transaction :

  Type de transaction  Nombre d'annonces
0                 NaN               1539
1               vente               1111
2            location                347

Valeurs manquantes : 1539

In [21]:

print("Répartition des annonces par devise :")

display(
    annonces_conformes["devise"]
    .value_counts(dropna=False)
    .rename_axis("Devise")
    .reset_index(name="Nombre d'annonces")
)

Répartition des annonces par devise :

      Devise  Nombre d'annonces
0        NaN               2134
1       FCFA                688
2  FCFA/mois                175


#### 8. Conclusion générale

L'analyse exploratoire a porté sur 2 997 annonces immobilières conformes issues de cinq sources différentes : plateforme, agence, particuliers, historique et notaires.

Les principales observations sont les suivantes :

- Les prix et les surfaces présentent une dispersion importante.
- Des doublons et des identifiants répétés ont été détectés.
- Certaines catégories immobilières présentent des variations d'écriture.
- Les annonces sont réparties entre plusieurs villes et catégories de biens.
- 51,35 % des annonces ne renseignent pas leur type de transaction.
- 71,20 % des annonces ne renseignent pas leur devise.

Ces constats montrent que, malgré le processus de nettoyage et de validation, certaines limites persistent dans les données.

Des améliorations peuvent être envisagées concernant la normalisation des catégories, la gestion des doublons et la complétude des informations relatives aux transactions et aux devises.

Cette analyse constitue une base pour améliorer la qualité des données et faciliter leur exploitation dans de futures analyses immobilières.